CivilRegistry_MVC/Models/Statistics.cs
using System;
using CivilRegistry_MVC.Models;
using CivilRegistry_MVC.Controllers;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;


namespace CivilRegistry_MVC.Models
{
    public class Statistics
    {
        private static CivilRegistryModel db = new CivilRegistryModel();

        public static int BirthNumber()
        {
            return db.People.Count();
        }

        public static int DeathNumber()
        {
            return db.DeathCertificates.Count();
        }

        public static int MarriageNumber()
        {
            return db.MarriageCertificates.Count();
        }

        public static int MigrationNumber()
        {
            return db.Passports.Count();
        }
        public static int CalculateAge(DateTime Birthday)
        {
            int age = DateTime.Now.Year - Birthday.Year;
            if (DateTime.Now.DayOfYear < Birthday.DayOfYear)
            { age -= 1; }
            return age;
        }

    }
}

CivilRegistry_MVC/Controllers/StatisticsController.cs
using CivilRegistry_MVC.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CivilRegistry_MVC.Controllers
{
    public class StatisticsController : Controller
    {
        private CivilRegistryModel db = new CivilRegistryModel();

        // GET: Statistics
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult OpcionalStatistics(string from, string to, string gender, string employmentStatus, string qualification, string healthCondition)
        {
            List<Person> GetSpecificPeople = new List<Person>();

            if (from != null && to != null)
            {
                int fromInt = int.Parse(from);
                int toInt = int.Parse(to);
                foreach (var item in db.People)
                {
                    if (Statistics.CalculateAge(item.Birthday) >= fromInt && Statistics.CalculateAge(item.Birthday) <= toInt)
                    {
                        if ((gender == "" || gender == item.Gender) && (employmentStatus == "" || employmentStatus == item.EmploymentStatus) && (qualification == "" ||
                            qualification == item.Qualification) && (healthCondition == "" || healthCondition == item.HealthCondition))
                        {
                            GetSpecificPeople.Add(item);
                        }
                    }
                }
                return View(GetSpecificPeople.ToList());
            }
            return View(db.People.ToList());
        }

        public ActionResult NumericalStatistics()
        {
            return View();
        }

        public ActionResult Searching(string option, string search)
        {
            if (option == "PersonalNumber")
            {
                return View(db.People.Where(x => x.PersonalNumber.StartsWith(search) || search == null).ToList());
            }
            else if (option == "FirstName")
            {
                return View(db.People.Where(x => x.FirstName.Contains(search) || search == null).ToList());
            }
            else if (option == "LastName")
            {
                return View(db.People.Where(x => x.LastName.StartsWith(search) || search == null).ToList());
            }
            else if (option == "Email")
            {
                return View(db.People.Where(x => x.Email.StartsWith(search) || search == null).ToList());
            }
            else if (option == "Address")
            {
                return View(db.People.Where(x => x.Address.StartsWith(search) || search == null).ToList());
            }
            else if (option == "BirthPlace")
            {
                return View(db.People.Where(x => x.BirthPlace.StartsWith(search) || search == null).ToList());
            }
            else if (option == "Municipality")
            {
                return View(db.People.Where(x => x.Municipality.StartsWith(search) || search == null).ToList());
            }
            else if (option == "Nationality")
            {
                return View(db.People.Where(x => x.Nationality.StartsWith(search) || search == null).ToList());
            }

            else return View(db.People.ToList());

        }
    }
}

CivilRegistry_MVC/Views/Statistics/NumericalStatistics.cshtml
@using CivilRegistry_MVC.Models;
@{CivilRegistryModel db = new CivilRegistryModel(); }
@{
        ViewBag.Title = "NumericalStatistics";
}

<h1>Statistikat Numerike:</h1>

<br/>

<p>Numri i Lindjeve eshte: @Statistics.BirthNumber()</p>
<p>Numri i Vdekjeve eshte: @Statistics.DeathNumber()</p>
<p>Numri i Martesave eshte: @Statistics.MarriageNumber()</p>
<p>Numri i Migrimeve eshte: @Statistics.MigrationNumber()</p>

@Html.ActionLink("Back to List", "Index")

CivilRegistry_MVC/Views/Statistics/OpcionalStatistics.cshtml
@model IEnumerable<CivilRegistry_MVC.Person>

@{
    ViewBag.Title = "OpcionalStatistics";
}

<h2>Opcional Statistics</h2>
<br />


<form>
    <table class="table">
        <tr>
            <td>
                <label for="from">From:</label>
                @Html.TextBox("from", null, new { style = "width:50px", required = "h" })
                <label for="to">To:</label>
                @Html.TextBox("to", null, new { style = "width:50px", required = "h" })

                <input type="submit" value="Submit">
            </td>
        </tr>
        <tr>
            <td>
                <div class="form-group">
                    Choose Gender
                    <select class="form-control" name="gender">
                        <option value="">None</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
            </td>

            <td>
                <div class="form-group">
                    Choose Status of Employment
                    <select class="form-control" name="employmentStatus">
                        <option value="">None</option>
                        <option value="Employed">Employed</option>
                        <option value="Unemployed">Unemployed</option>
                    </select>
                </div>
            </td>

            <td>
                <div class="form-group">
                    Choose Qualification
                    <select class="form-control" name="qualification">
                        <option value="">None</option>
                        <option value="Bachelor">Bachelor</option>
                        <option value="Prof.Training">Profesional Training</option>
                        <option value="Other">Other</option>
                    </select>
                </div>
            </td>

            <td>
                <div class="form-group">
                    Choose Condition of Health
                    <select class="form-control" name="healthCondition">
                        <option value="">None</option>
                        <option value="Positive">Positive</option>
                        <option value="Negative">Negative</option>
                    </select>
                </div>
            </td>
        </tr>
    </table>
</form>

<table class="table" border="2">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PersonalNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Municipality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nationality)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.EmploymentStatus)*@
            EmpStatus
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qualification)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.HealthCondition)*@
            HealthCo
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="height:30px">
            <td>
                @Html.DisplayFor(modelItem => item.PersonalNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Birthday)*@
                @string.Format("{0:dd/MMM/yyyy}", Convert.ToDateTime(Html.DisplayFor(modelItem => item.Birthday).ToString()))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthPlace)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Municipality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmploymentStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qualification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HealthCondition)
            </td>
        </tr>
    }

</table>

CivilRegistry_MVC/Views/Statistics/Searching.cshtml
@model IEnumerable<CivilRegistry_MVC.Person>


@{
    ViewBag.Title = "Searching";
}

<h2>Searching</h2>

@using (Html.BeginForm("Searching", "Statistics", FormMethod.Get))
{
    <b> Search Option: </b>
    @Html.RadioButton("option", "PersonalNumber") <text>PersonalNumber</text>
    @Html.RadioButton("option", "FirstName") <text>FirstName</text>
    @Html.RadioButton("option", "LastName") <text> LastName </text>
    @Html.RadioButton("option", "Email")<text>Email</text>
    @Html.RadioButton("option", "Address")<text>Address</text>
    @Html.RadioButton("option", "BirthPlace")<text>BirthPlace</text>
    @Html.RadioButton("option", "Municipality")<text>Municipality</text>
    @Html.RadioButton("option", "Nationality")<text>Nationality</text>

    @Html.TextBox("search")
    <input type="submit" name="submit" value="Search" />
}

<br />
<table class="table" border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PersonalNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Municipality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nationality)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.EmploymentStatus)*@
            EmpStatus
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qualification)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.HealthCondition)*@
            HealthCo
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="height:30px">
            <td>
                @Html.DisplayFor(modelItem => item.PersonalNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Birthday)*@
                @string.Format("{0:dd/MMM/yyyy}", Convert.ToDateTime(Html.DisplayFor(modelItem => item.Birthday).ToString()))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthPlace)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Municipality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmploymentStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qualification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HealthCondition)
            </td>
        </tr>
    }

</table>

<br />